# builds the kprobes example kernel modules;
# then to use one (as root):  insmod <module_name.ko>

obj-m += jprobe1.o acpica/
#jprobe1-y = jprobe_example.o acpica/utdecode.o acpica/utmisc.o acpica/utglobal.o acpica/utalloc.o
jprobe1-y = jprobe_example.o 
